---
title: "ISCAM Package"
author: "Noelle Pablo"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ISCAM Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This package contains a variety of R functions to accompany the introductory statistics textbook, _Investigating Statistiscal Concepts, Applications, and Methods_ (ISCAM), written by Dr. Allan Rossman and Dr. Beth Chance. These functions are to aid students in their investigations, assignments, and projects. The functions are categorized into 5 groups: Data Visualization, Summary Statistics, Hypothesis Testing, Quantiles, Rejection Regions & Power, Probability Distributions, Normal Approximations, and Overlaying Probability Distributions.

## Data Visualization
- iscam_boxplot
- iscam_dotplot

## Summary Statistics
- iscam_summary

## Hypothesis Testing
- iscam_onepropztest
- iscam_twopropztest
- iscam_onesamplet
- iscam_twosamplet
- iscam_binomtest

## Quantiles
- iscam_invbinom
- iscam_invnorm
- iscam_invt

## Rejection Regions & Power
- iscam_binompower
- iscam_normpower

## Probability Distributions
- iscam_binom
- iscam_binomprob
- iscam_hyperprob
- iscam_normprob
- iscam_chisqprob
- iscam_tprob

## Normal Approximations
- iscam_binomnorm
- iscam_hypernorm

## Overlaying Probability Distributions
- iscam_addexp
- iscam_addlnorm
- iscam_addnorm
- iscam_addt
- iscam_addtnorm